version: "3"
services:
  tibco_base: &tibco_base
    build:
      context: .
      dockerfile: docker/java/Dockerfile
    network_mode: host
    volumes:
      - ./tibco:/tibco
      - ./data:/data
    env_file:
      - ./tibco/src/main/resources/.env

  tibco_lpo_data:
    <<: *tibco_base
    environment:
      - AMM_QUEUE=AMM.LPOData
    depends_on:
      - tibco_base

  tibco_publish_dc_standard:
    <<: *tibco_base
    environment:
      - AMM_QUEUE=AMM.LPOData
    depends_on:
      - tibco_base
  tibco_pro_data:
    <<: *tibco_base
    environment:
      - AMM_QUEUE=AMM.RROData
    depends_on:
      - tibco_base
  tibco_publish_lp_totalizer:
    <<: *tibco_base
    environment:
      - AMM_QUEUE=AMM.PublishLPTotalizer
    depends_on:
      - tibco_base
