version: "3"
services:
  vsftpd:
    ports:
      - '21:21'
      - '4559-4564:4559-4564'
    env_file:
      - .env
    volumes:
      - ./data:/srv/${FTP_USER}
    image: panubo/vsftpd:latest

  tibco_base: &tibco_base
    build:
      context: .
      dockerfile: docker/java/Dockerfile
    network_mode: host
    volumes:
      - ./tibco:/tibco
      - ./.env:/tibco/src/main/resources/.env
      - ./data:/data
    env_file:
      - .env

  tibco_lpo_data:
    <<: *tibco_base
    environment:
      - AMM_QUEUE=AMM.LPOData
    depends_on:
      - tibco_base

  tibco_publish_lp_totalizer:
    <<: *tibco_base
    environment:
      - AMM_QUEUE=ECASA.AMM.WBCMOData
    depends_on:
      - tibco_base

  stg:
    image: input_stg
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./stg:/stg