version: "3"
services:
  vsftpd:
    ports:
      - '21:21'
      - '4500-4600:4500-4600'
    env_file:
      - .env
    volumes:
      - ./data:/srv/${FTP_USER}
    image: panubo/vsftpd:latest
    network_mode: "host"

  tibco_base: &tibco_base
    build:
      context: .
      dockerfile: docker/java/Dockerfile
    network_mode: host
    volumes:
      - ./tibco:/tibco
      - ./.env:/tibco/src/main/resources/.env
      - ./data:/data
    env_file:
      - .env
  tibco_publish_lp_totalizer:
    <<: *tibco_base
    environment:
      - AMM_QUEUE=ECASA.AMM.WBCMOData
    depends_on:
      - tibco_base
